In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
a = np.arange(6)

In [6]:
a

array([0, 1, 2, 3, 4, 5])

In [8]:
type(a)

numpy.ndarray

In [9]:
a[0]

0

In [10]:
a[1]

1

In [11]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [12]:
a2 = a[np.newaxis, :]

In [13]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [14]:
a2.shape

(1, 6)

In [15]:
a.shape

(6,)

In [16]:
#배열

In [17]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[0]

array([1, 2, 3, 4])

In [20]:
a[1]

array([5, 6, 7, 8])

In [21]:
a[2]

array([ 9, 10, 11, 12])

In [22]:
a = np.array([1, 2, 3])

In [23]:
np.zeros(2)

array([0., 0.])

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.empty(2)

array([0., 0.])

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [31]:
np.arange(2, 8, 2)

array([2, 4, 6])

In [32]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
b = np.ones(2, dtype=np.int64)

In [34]:
b

array([1, 1], dtype=int64)

In [37]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8, ])

In [38]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a = np.sort(arr)

In [40]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
arr = np.sort(arr)

In [42]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [44]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [48]:
x

array([[1, 2],
       [3, 4]])

In [49]:
y

array([[5, 6]])

In [50]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
c = np.concatenate((x,y), axis=0)

In [52]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
#size

In [54]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [55]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [57]:
array_example.ndim

3

In [58]:
array_example.size

24

In [59]:
array_example.shape

(3, 2, 4)

In [60]:
a = np.arange(6)

In [61]:
a

array([0, 1, 2, 3, 4, 5])

In [62]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
a.reshape(2,5)

ValueError: cannot reshape array of size 6 into shape (2,5)

In [64]:
a.reshape(2, 2)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [65]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [66]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [68]:
#1D -> 2D

In [75]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [77]:
a2 = a[np.newaxis, :]

In [78]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [79]:
a2.shape

(1, 6)

In [80]:
row_vector = a[np.newaxis, :]

In [81]:
row_vector.shape

(1, 6)

In [82]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [83]:
#slicing

In [84]:
data = np.array([1, 2, 3])

In [85]:
data

array([1, 2, 3])

In [86]:
data[0]

1

In [87]:
data[1]

2

In [88]:
data[0:2]

array([1, 2])

In [89]:
data[1:]

array([2, 3])

In [90]:
data[-2:]

array([2, 3])

In [91]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [92]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [94]:
print(a[a<5])

[1 2 3 4]


In [95]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [96]:
b = 2

In [98]:
if b > 5:
    print("에구 너무 큰디유?")

else:
    print("좋아유")

좋아유


In [99]:
a[a < 5]

array([1, 2, 3, 4])

In [100]:
a >= 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [101]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
a%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [103]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [104]:
(a > 2) & (a < 11)

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [107]:
(a > 5) | (a == 5)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [108]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [109]:
np.nonzero(a < 5)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [110]:
b = np.nonzero(a < 5)

In [111]:
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [112]:
zip(b[0], b[1])

In [113]:
list(zip(b[0], b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [114]:
list_of_cordinates = list(zip(b[0], b[1]))

In [115]:
list_of_cordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [117]:
for coord in list_of_cordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [119]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [120]:
arrl = a[3:8]

In [121]:
arrl

array([4, 5, 6, 7, 8])

In [123]:
a1 = np.array([[1, 1],
               [2, 2]])

In [124]:
a2 = np.array([[3, 3],
               [4, 4]])

In [125]:
a1

array([[1, 1],
       [2, 2]])

In [126]:
a2

array([[3, 3],
       [4, 4]])

In [128]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [133]:
a = np.arange(1, 15)

In [134]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [135]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [136]:
np.arange(1, 15).reshape(2, 7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [137]:
x = np.arange(1, 25).reshape(2,12)

In [138]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [139]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [140]:
np.hsplit(x, 3)[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [141]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [142]:
np.hsplit(x, (3, 5))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [156]:
#copy

In [143]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [144]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [145]:
a[1,1]

6

In [146]:
a[2,3]

12

In [147]:
a[2,:]

array([ 9, 10, 11, 12])

In [148]:
a[:,2]

array([ 3,  7, 11])

In [149]:
a[0,:]

array([1, 2, 3, 4])

In [150]:
b1 = a[0,:]

In [151]:
b1

array([1, 2, 3, 4])

In [152]:
b1[0] = 99

In [153]:
b1

array([99,  2,  3,  4])

In [154]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [166]:
b2 = a.copy()

In [167]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [168]:
b2[0] = 99

In [169]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [170]:
b2

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [171]:
data = np.array([1, 2])

In [172]:
ones = np.ones(2, dtype=int)

In [173]:
data + ones

array([2, 3])

In [174]:
data - ones

array([0, 1])

In [177]:
data * data

array([1, 4])

In [178]:
data / data

array([1., 1.])

In [184]:
a = np.array([1, 2, 3, 4])

In [185]:
a

array([1, 2, 3, 4])

In [186]:
a.sum()

10

In [187]:
b = [1, 321, 3, 4]

In [188]:
len(b)

4

In [189]:
b.sort()

In [190]:
b

[1, 3, 4, 321]

In [193]:
b = np.array([[1, 1], [2, 2]])

In [194]:
b.sum(axis=0)

array([3, 3])

In [195]:
b

array([[1, 1],
       [2, 2]])

In [196]:
b.sum(axis=1)

array([2, 4])

In [197]:
#곱하기

In [198]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [199]:
#max

In [201]:
a = np.array([1, 2, 3, 4])

In [202]:
a.max()

4

In [203]:
a.min()

1

In [204]:
b

array([[1, 1],
       [2, 2]])

In [205]:
b = np.array([[1, 4], [2, 7]])

In [206]:
b

array([[1, 4],
       [2, 7]])

In [207]:
b.min()

1

In [208]:
b.min(axis=0)

array([1, 4])

In [209]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [211]:
a.min()

0.05093587

In [212]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [213]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [214]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [215]:
data[0, 1]

2

In [216]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [217]:
data[0:2, 0]

array([1, 3])

In [218]:
data.min()

1

In [225]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [226]:
data.max(axis=0)


array([5, 6])

In [227]:
data.max(axis=1)


array([2, 5, 6])

In [228]:
data = np.array([[1, 2], [3, 4]])

In [229]:
ones = np.array([[1, 1], [1, 1]])

In [230]:
data + ones

array([[2, 3],
       [4, 5]])

In [231]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [232]:
ones_row = np.array([[1, 1]])

In [233]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [234]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [235]:
np.ones(3)

array([1., 1., 1.])

In [238]:
np.zeros(3)

array([0., 0., 0.])

In [239]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [245]:
rng = np.random.default_rng()

In [246]:
rng.random(3) 

array([0.66770028, 0.39105602, 0.25805436])

In [247]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [248]:
rng.random((3, 2)) 

array([[0.22602855, 0.14434178],
       [0.53139586, 0.68292944],
       [0.40725586, 0.81702275]])

In [249]:
#random

In [250]:
rng.integers(5, size=(2, 4)) 

array([[3, 3, 2, 0],
       [3, 4, 3, 3]], dtype=int64)

In [251]:
#unique

In [219]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])


In [221]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [224]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [253]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [254]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [255]:
arr = np.arange(6).reshape((2, 3))

In [256]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [257]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [259]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [260]:
#reverse

In [262]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [263]:
reversed_arr = np.flip(arr)

In [264]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [265]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [266]:
reversed_arr = np.flip(arr_2d)

In [267]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [268]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [269]:
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [270]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [271]:
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [272]:
arr_2d[1] = np.flip(arr_2d[1])

In [273]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [274]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [275]:
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [276]:
#Reshaping and flattening multidimensional arrays

In [277]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [278]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [279]:
a1 = x.flatten()
a1[0] = 99

In [280]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [281]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [282]:
a2 = x.ravel()

In [283]:
a2[0] = 98

In [284]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [285]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
